name: Build Kernel
on:
  push:
    branches:    
      - main

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: sudo bash build.sh

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
